// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package universalsdk

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV2(in *jlexer.Lexer, out *apiResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payload":
			out.Payload = string(in.String())
		case "swhanedl":
			out.Swhanedl = string(in.String())
		case "context":
			out.Context = string(in.String())
		case "timeZone":
			out.TimeZone = string(in.String())
		case "clientId":
			out.ClientId = string(in.String())
		case "headers":
			if in.IsNull() {
				in.Skip()
				out.Headers = nil
			} else {
				if out.Headers == nil {
					out.Headers = new(Headers)
				}
				(*out.Headers).UnmarshalEasyJSON(in)
			}
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV2(out *jwriter.Writer, in apiResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix[1:])
		out.String(string(in.Payload))
	}
	if in.Swhanedl != "" {
		const prefix string = ",\"swhanedl\":"
		out.RawString(prefix)
		out.String(string(in.Swhanedl))
	}
	if in.Context != "" {
		const prefix string = ",\"context\":"
		out.RawString(prefix)
		out.String(string(in.Context))
	}
	if in.TimeZone != "" {
		const prefix string = ",\"timeZone\":"
		out.RawString(prefix)
		out.String(string(in.TimeZone))
	}
	if in.ClientId != "" {
		const prefix string = ",\"clientId\":"
		out.RawString(prefix)
		out.String(string(in.ClientId))
	}
	{
		const prefix string = ",\"headers\":"
		out.RawString(prefix)
		if in.Headers == nil {
			out.RawString("null")
		} else {
			(*in.Headers).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v apiResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v apiResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *apiResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *apiResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV2(l, v)
}
func easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV21(in *jlexer.Lexer, out *SensorInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "abck":
			out.Abck = string(in.String())
		case "bmsz":
			out.Bmsz = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "pageUrl":
			out.PageUrl = string(in.String())
		case "userAgent":
			out.UserAgent = string(in.String())
		case "script":
			out.Script = string(in.String())
		case "scriptUrl":
			out.ScriptUrl = string(in.String())
		case "acceptLanguage":
			out.AcceptLanguage = string(in.String())
		case "ip":
			out.IP = string(in.String())
		case "context":
			out.Context = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV21(out *jwriter.Writer, in SensorInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"abck\":"
		out.RawString(prefix[1:])
		out.String(string(in.Abck))
	}
	{
		const prefix string = ",\"bmsz\":"
		out.RawString(prefix)
		out.String(string(in.Bmsz))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"pageUrl\":"
		out.RawString(prefix)
		out.String(string(in.PageUrl))
	}
	{
		const prefix string = ",\"userAgent\":"
		out.RawString(prefix)
		out.String(string(in.UserAgent))
	}
	{
		const prefix string = ",\"script\":"
		out.RawString(prefix)
		out.String(string(in.Script))
	}
	{
		const prefix string = ",\"scriptUrl\":"
		out.RawString(prefix)
		out.String(string(in.ScriptUrl))
	}
	{
		const prefix string = ",\"acceptLanguage\":"
		out.RawString(prefix)
		out.String(string(in.AcceptLanguage))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	{
		const prefix string = ",\"context\":"
		out.RawString(prefix)
		out.String(string(in.Context))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SensorInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV21(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SensorInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV21(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SensorInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV21(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SensorInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV21(l, v)
}
func easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV22(in *jlexer.Lexer, out *SbsdInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "index":
			out.Index = int(in.Int())
		case "userAgent":
			out.UserAgent = string(in.String())
		case "uuid":
			out.Uuid = string(in.String())
		case "pageUrl":
			out.PageUrl = string(in.String())
		case "o":
			out.OCookie = string(in.String())
		case "script":
			out.Script = string(in.String())
		case "acceptLanguage":
			out.AcceptLanguage = string(in.String())
		case "ip":
			out.IP = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV22(out *jwriter.Writer, in SbsdInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Index))
	}
	{
		const prefix string = ",\"userAgent\":"
		out.RawString(prefix)
		out.String(string(in.UserAgent))
	}
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix)
		out.String(string(in.Uuid))
	}
	{
		const prefix string = ",\"pageUrl\":"
		out.RawString(prefix)
		out.String(string(in.PageUrl))
	}
	{
		const prefix string = ",\"o\":"
		out.RawString(prefix)
		out.String(string(in.OCookie))
	}
	{
		const prefix string = ",\"script\":"
		out.RawString(prefix)
		out.String(string(in.Script))
	}
	{
		const prefix string = ",\"acceptLanguage\":"
		out.RawString(prefix)
		out.String(string(in.AcceptLanguage))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SbsdInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV22(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SbsdInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV22(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SbsdInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV22(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SbsdInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV22(l, v)
}
func easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV23(in *jlexer.Lexer, out *PixelInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userAgent":
			out.UserAgent = string(in.String())
		case "htmlVar":
			out.HTMLVar = string(in.String())
		case "scriptVar":
			out.ScriptVar = string(in.String())
		case "acceptLanguage":
			out.AcceptLanguage = string(in.String())
		case "ip":
			out.IP = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV23(out *jwriter.Writer, in PixelInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userAgent\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserAgent))
	}
	{
		const prefix string = ",\"htmlVar\":"
		out.RawString(prefix)
		out.String(string(in.HTMLVar))
	}
	{
		const prefix string = ",\"scriptVar\":"
		out.RawString(prefix)
		out.String(string(in.ScriptVar))
	}
	{
		const prefix string = ",\"acceptLanguage\":"
		out.RawString(prefix)
		out.String(string(in.AcceptLanguage))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PixelInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV23(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PixelInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV23(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PixelInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV23(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PixelInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV23(l, v)
}
func easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV24(in *jlexer.Lexer, out *Headers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "sec-ch-device-memory":
			out.DeviceMemory = string(in.String())
		case "sec-ch-ua-mobile":
			out.Mobile = string(in.String())
		case "sec-ch-ua-arch":
			out.Arch = string(in.String())
		case "sec-ch-ua-platform":
			out.Platform = string(in.String())
		case "sec-ch-ua-model":
			out.Model = string(in.String())
		case "sec-ch-ua-full-version-list":
			out.FullVersionList = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV24(out *jwriter.Writer, in Headers) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sec-ch-device-memory\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceMemory))
	}
	{
		const prefix string = ",\"sec-ch-ua-mobile\":"
		out.RawString(prefix)
		out.String(string(in.Mobile))
	}
	{
		const prefix string = ",\"sec-ch-ua-arch\":"
		out.RawString(prefix)
		out.String(string(in.Arch))
	}
	{
		const prefix string = ",\"sec-ch-ua-platform\":"
		out.RawString(prefix)
		out.String(string(in.Platform))
	}
	{
		const prefix string = ",\"sec-ch-ua-model\":"
		out.RawString(prefix)
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"sec-ch-ua-full-version-list\":"
		out.RawString(prefix)
		out.String(string(in.FullVersionList))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Headers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV24(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Headers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV24(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Headers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV24(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Headers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV24(l, v)
}
func easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV25(in *jlexer.Lexer, out *DynamicInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "script":
			out.Script = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV25(out *jwriter.Writer, in DynamicInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"script\":"
		out.RawString(prefix[1:])
		out.String(string(in.Script))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DynamicInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV25(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DynamicInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSoldOutSolutionsUniversalSdkGoV25(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DynamicInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV25(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DynamicInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSoldOutSolutionsUniversalSdkGoV25(l, v)
}
